# coding: utf-8

"""
    Workato Platform API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self


class CustomConnectorCreateRequest(BaseModel):
    """Request body for creating a custom connector.""" # noqa: E501
    title: str = Field(description="Connector title")
    code: str = Field(description="Connector source code (Ruby, max 10MB)")
    description: Optional[str] = Field(default=None, description="Connector description (markdown supported)")
    logo: Optional[str] = Field(default=None, description="Base64-encoded logo image")
    note: Optional[str] = Field(default=None, description="Version note")
    __properties: ClassVar[List[str]] = ["title", "code", "description", "logo", "note"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        if not isinstance(obj, dict):
            return cls.model_validate(obj)
        return cls.model_validate(obj)
