# coding: utf-8

"""
    Workato Platform API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self


class CustomOAuthProfileData(BaseModel):
    """OAuth client data within a profile.""" # noqa: E501
    client_id: Optional[str] = Field(default=None, description="OAuth client ID")
    client_secret: Optional[str] = Field(default=None, description="OAuth client secret")
    token: Optional[str] = Field(default=None, description="Token (Slack only)")
    __properties: ClassVar[List[str]] = ["client_id", "client_secret", "token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        if not isinstance(obj, dict):
            return cls.model_validate(obj)
        return cls.model_validate(obj)


class CustomOAuthProfile(BaseModel):
    """Custom OAuth Profile.""" # noqa: E501
    id: Optional[int] = Field(default=None, description="Profile ID")
    user_id: Optional[int] = Field(default=None, description="User ID")
    name: Optional[str] = Field(default=None, description="Profile name")
    provider: Optional[str] = Field(default=None, description="App provider name")
    data: Optional[CustomOAuthProfileData] = Field(default=None, description="OAuth data")
    shared_accounts_count: Optional[int] = Field(default=None)
    oem_customers_count: Optional[int] = Field(default=None)
    created_at: Optional[str] = Field(default=None, description="Created timestamp")
    updated_at: Optional[str] = Field(default=None, description="Updated timestamp")
    __properties: ClassVar[List[str]] = [
        "id", "user_id", "name", "provider", "data",
        "shared_accounts_count", "oem_customers_count",
        "created_at", "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.data:
            _dict["data"] = self.data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        if not isinstance(obj, dict):
            return cls.model_validate(obj)
        _obj = cls.model_validate({
            "id": obj.get("id"),
            "user_id": obj.get("user_id"),
            "name": obj.get("name"),
            "provider": obj.get("provider"),
            "data": CustomOAuthProfileData.from_dict(obj.get("data")),
            "shared_accounts_count": obj.get("shared_accounts_count"),
            "oem_customers_count": obj.get("oem_customers_count"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
        })
        return _obj


class CustomOAuthProfileListResponse(BaseModel):
    """Response from listing custom OAuth profiles.""" # noqa: E501
    result: Optional[List[CustomOAuthProfile]] = Field(default=None)
    __properties: ClassVar[List[str]] = ["result"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_dict(self) -> Dict[str, Any]:
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.result:
            _dict["result"] = [p.to_dict() for p in self.result]
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        if not isinstance(obj, dict):
            return cls.model_validate(obj)
        return cls.model_validate({
            "result": [
                CustomOAuthProfile.from_dict(p)
                for p in obj["result"]
            ] if obj.get("result") else None,
        })
