# coding: utf-8

"""
    Workato Platform API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self


class CustomConnectorResponse(BaseModel):
    """Response from creating/updating a custom connector.""" # noqa: E501
    id: Optional[int] = Field(default=None, description="Connector ID")
    title: Optional[str] = Field(default=None, description="Connector title")
    name: Optional[str] = Field(default=None, description="Connector name")
    latest_released_version: Optional[int] = Field(default=None, description="Latest released version number")
    latest_released_version_note: Optional[str] = Field(default=None, description="Latest version note")
    __properties: ClassVar[List[str]] = [
        "id", "title", "name", "latest_released_version", "latest_released_version_note"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        excluded_fields: set[str] = set()
        return self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        if obj is None:
            return None
        if not isinstance(obj, dict):
            return cls.model_validate(obj)
        return cls.model_validate(obj)
