# coding: utf-8

"""
    Workato Platform API

    Job model for the Workato Platform API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self


class Job(BaseModel):
    """
    Job
    """ # noqa: E501
    id: Optional[str] = Field(default=None, description="Job ID")
    completed_at: Optional[str] = Field(default=None, description="Timestamp when the job completed")
    started_at: Optional[str] = Field(default=None, description="Timestamp when the job started")
    title: Optional[str] = Field(default=None, description="Job title")
    is_poll_error: Optional[bool] = Field(default=None, description="Whether the job is a polling error")
    error: Optional[str] = Field(default=None, description="Error message if the job failed")
    is_error: Optional[bool] = Field(default=None, description="Whether the job encountered an error")
    status: Optional[str] = Field(default=None, description="Job status")
    recipe_id: Optional[int] = Field(default=None, description="Recipe ID this job belongs to")
    calling_recipe_id: Optional[int] = Field(default=None, description="ID of the calling recipe")
    calling_job_id: Optional[str] = Field(default=None, description="ID of the calling job")
    root_recipe_id: Optional[int] = Field(default=None, description="ID of the root recipe in a chain")
    root_job_id: Optional[str] = Field(default=None, description="ID of the root job in a chain")
    master_job_id: Optional[str] = Field(default=None, description="ID of the master job")
    __properties: ClassVar[List[str]] = [
        "id", "completed_at", "started_at", "title", "is_poll_error",
        "error", "is_error", "status", "recipe_id", "calling_recipe_id",
        "calling_job_id", "root_recipe_id", "root_job_id", "master_job_id"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias."""
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "completed_at": obj.get("completed_at"),
            "started_at": obj.get("started_at"),
            "title": obj.get("title"),
            "is_poll_error": obj.get("is_poll_error"),
            "error": obj.get("error"),
            "is_error": obj.get("is_error"),
            "status": obj.get("status"),
            "recipe_id": obj.get("recipe_id"),
            "calling_recipe_id": obj.get("calling_recipe_id"),
            "calling_job_id": obj.get("calling_job_id"),
            "root_recipe_id": obj.get("root_recipe_id"),
            "root_job_id": obj.get("root_job_id"),
            "master_job_id": obj.get("master_job_id"),
        })
        return _obj
