# coding: utf-8

"""
    Workato Platform API

    JobDetail model for the Workato Platform API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self

from workato_platform_cli.client.workato_api.models.job_line import JobLine


class JobDetail(BaseModel):
    """
    JobDetail - includes execution step details (lines)
    """ # noqa: E501
    id: Optional[str] = Field(default=None, description="Job ID")
    handle: Optional[str] = Field(default=None, description="Job handle")
    completed_at: Optional[str] = Field(default=None, description="Timestamp when the job completed")
    started_at: Optional[str] = Field(default=None, description="Timestamp when the job started")
    title: Optional[str] = Field(default=None, description="Job title")
    is_poll_error: Optional[bool] = Field(default=None, description="Whether the job is a polling error")
    error: Optional[str] = Field(default=None, description="Error message if the job failed")
    is_error: Optional[bool] = Field(default=None, description="Whether the job encountered an error")
    is_repeat: Optional[bool] = Field(default=None, description="Whether this job is a repeat/rerun")
    is_test: Optional[bool] = Field(default=None, description="Whether this job is a test run")
    is_test_case_job: Optional[bool] = Field(default=None, description="Whether this job is a test case job")
    status: Optional[str] = Field(default=None, description="Job status")
    recipe_id: Optional[int] = Field(default=None, description="Recipe ID this job belongs to")
    calling_recipe_id: Optional[int] = Field(default=None, description="ID of the calling recipe")
    calling_job_id: Optional[str] = Field(default=None, description="ID of the calling job")
    calling_job_handle: Optional[str] = Field(default=None, description="Handle of the calling job")
    root_recipe_id: Optional[int] = Field(default=None, description="ID of the root recipe in a chain")
    root_job_id: Optional[str] = Field(default=None, description="ID of the root job in a chain")
    master_job_id: Optional[str] = Field(default=None, description="ID of the master job")
    master_job_handle: Optional[str] = Field(default=None, description="Handle of the master job")
    lines: Optional[List[JobLine]] = Field(default=None, description="Execution step details")
    __properties: ClassVar[List[str]] = [
        "id", "handle", "completed_at", "started_at", "title",
        "is_poll_error", "error", "is_error", "is_repeat", "is_test",
        "is_test_case_job", "status", "recipe_id", "calling_recipe_id",
        "calling_job_id", "calling_job_handle", "root_recipe_id",
        "root_job_id", "master_job_id", "master_job_handle", "lines"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias."""
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        _items = []
        if self.lines:
            for _item in self.lines:
                if _item:
                    _items.append(_item.to_dict())
            _dict['lines'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "handle": obj.get("handle"),
            "completed_at": obj.get("completed_at"),
            "started_at": obj.get("started_at"),
            "title": obj.get("title"),
            "is_poll_error": obj.get("is_poll_error"),
            "error": obj.get("error"),
            "is_error": obj.get("is_error"),
            "is_repeat": obj.get("is_repeat"),
            "is_test": obj.get("is_test"),
            "is_test_case_job": obj.get("is_test_case_job"),
            "status": obj.get("status"),
            "recipe_id": obj.get("recipe_id"),
            "calling_recipe_id": obj.get("calling_recipe_id"),
            "calling_job_id": obj.get("calling_job_id"),
            "calling_job_handle": obj.get("calling_job_handle"),
            "root_recipe_id": obj.get("root_recipe_id"),
            "root_job_id": obj.get("root_job_id"),
            "master_job_id": obj.get("master_job_id"),
            "master_job_handle": obj.get("master_job_handle"),
            "lines": [JobLine.from_dict(_item) for _item in obj["lines"]] if obj.get("lines") is not None else None,
        })
        return _obj
