# coding: utf-8

"""
    Workato Platform API

    JobLine model for the Workato Platform API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self


class JobLine(BaseModel):
    """
    JobLine - a single execution step within a job
    """ # noqa: E501
    recipe_line_number: Optional[int] = Field(default=None, description="Line number in the recipe")
    adapter_name: Optional[str] = Field(default=None, description="Name of the adapter/connector used")
    adapter_operation: Optional[str] = Field(default=None, description="Operation performed")
    input: Optional[Dict[str, Any]] = Field(default=None, description="Input data for this step")
    output: Optional[Dict[str, Any]] = Field(default=None, description="Output data from this step")
    mask_data: Optional[bool] = Field(default=None, description="Whether data is masked")
    line_stat: Optional[Dict[str, Any]] = Field(default=None, description="Execution statistics")
    __properties: ClassVar[List[str]] = [
        "recipe_line_number", "adapter_name", "adapter_operation",
        "input", "output", "mask_data", "line_stat"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias."""
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recipe_line_number": obj.get("recipe_line_number"),
            "adapter_name": obj.get("adapter_name"),
            "adapter_operation": obj.get("adapter_operation"),
            "input": obj.get("input"),
            "output": obj.get("output"),
            "mask_data": obj.get("mask_data"),
            "line_stat": obj.get("line_stat"),
        })
        return _obj
