# coding: utf-8

"""
    Workato Platform API

    JobListResponse model for the Workato Platform API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Self

from workato_platform_cli.client.workato_api.models.job import Job


class JobListResponse(BaseModel):
    """
    JobListResponse
    """ # noqa: E501
    job_succeeded_count: Optional[int] = Field(default=None, description="Number of succeeded jobs")
    job_failed_count: Optional[int] = Field(default=None, description="Number of failed jobs")
    job_count: Optional[int] = Field(default=None, description="Total number of jobs")
    job_scope_count: Optional[int] = Field(default=None, description="Number of jobs in current scope")
    items: Optional[List[Job]] = Field(default=None, description="List of jobs")
    __properties: ClassVar[List[str]] = [
        "job_succeeded_count", "job_failed_count", "job_count",
        "job_scope_count", "items"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias."""
        excluded_fields: set[str] = set()
        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_succeeded_count": obj.get("job_succeeded_count"),
            "job_failed_count": obj.get("job_failed_count"),
            "job_count": obj.get("job_count"),
            "job_scope_count": obj.get("job_scope_count"),
            "items": [Job.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
        })
        return _obj
