# coding: utf-8

"""
    Workato Platform API

    Custom OAuth Profiles API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from workato_platform_cli.client.workato_api.models.custom_oauth_profile import (
    CustomOAuthProfile,
    CustomOAuthProfileListResponse,
)

from workato_platform_cli.client.workato_api.api_client import ApiClient, RequestSerialized


class CustomOAuthProfilesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def list_custom_oauth_profiles(
        self,
        page: Annotated[Optional[StrictInt], Field(description="Page number")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Page size")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CustomOAuthProfileListResponse:
        """List custom OAuth profiles"""

        _param = self._list_serialize(
            page=page, per_page=per_page,
            _request_auth=_request_auth, _content_type=_content_type,
            _headers=_headers, _host_index=_host_index,
        )
        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CustomOAuthProfileListResponse", '401': "Error",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data, response_types_map=_response_types_map,
        ).data

    def _list_serialize(self, page, per_page, _request_auth, _content_type, _headers, _host_index) -> RequestSerialized:
        _host = None
        _collection_formats: Dict[str, str] = {}
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        if page is not None:
            _query_params.append(('page', page))
        if per_page is not None:
            _query_params.append(('per_page', per_page))

        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])
        _auth_settings: List[str] = ['BearerAuth']

        return self.api_client.param_serialize(
            method='GET', resource_path='/api/custom_oauth_profiles',
            path_params=_path_params, query_params=_query_params,
            header_params=_header_params, body=_body_params,
            post_params=_form_params, files=_files,
            auth_settings=_auth_settings, collection_formats=_collection_formats,
            _host=_host, _request_auth=_request_auth,
        )

    @validate_call
    async def get_custom_oauth_profile(
        self,
        id: Annotated[StrictInt, Field(description="Profile ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CustomOAuthProfile:
        """Get a custom OAuth profile by ID"""

        _param = self._get_serialize(
            id=id, _request_auth=_request_auth, _content_type=_content_type,
            _headers=_headers, _host_index=_host_index,
        )
        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CustomOAuthProfile", '401': "Error", '404': "Error",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data, response_types_map=_response_types_map,
        ).data

    def _get_serialize(self, id, _request_auth, _content_type, _headers, _host_index) -> RequestSerialized:
        _host = None
        _collection_formats: Dict[str, str] = {}
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        if id is not None:
            _path_params['id'] = id

        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])
        _auth_settings: List[str] = ['BearerAuth']

        return self.api_client.param_serialize(
            method='GET', resource_path='/api/custom_oauth_profiles/{id}',
            path_params=_path_params, query_params=_query_params,
            header_params=_header_params, body=_body_params,
            post_params=_form_params, files=_files,
            auth_settings=_auth_settings, collection_formats=_collection_formats,
            _host=_host, _request_auth=_request_auth,
        )

    @validate_call
    async def create_custom_oauth_profile(
        self,
        name: Annotated[StrictStr, Field(description="Profile name")],
        provider: Annotated[StrictStr, Field(description="App provider name")],
        client_id: Annotated[StrictStr, Field(description="OAuth client ID")],
        client_secret: Annotated[StrictStr, Field(description="OAuth client secret")],
        token: Annotated[Optional[StrictStr], Field(description="Token (Slack only)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CustomOAuthProfile:
        """Create a custom OAuth profile"""

        _param = self._create_serialize(
            name=name, provider=provider, client_id=client_id,
            client_secret=client_secret, token=token,
            _request_auth=_request_auth, _content_type=_content_type,
            _headers=_headers, _host_index=_host_index,
        )
        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CustomOAuthProfile", '401': "Error",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data, response_types_map=_response_types_map,
        ).data

    def _create_serialize(self, name, provider, client_id, client_secret, token,
                          _request_auth, _content_type, _headers, _host_index) -> RequestSerialized:
        _host = None
        _collection_formats: Dict[str, str] = {}
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}

        body: Dict[str, Any] = {
            "name": name,
            "provider": provider,
            "data": {"client_id": client_id, "client_secret": client_secret},
        }
        if token is not None:
            body["data"]["token"] = token
        _body_params = body

        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])
        _header_params['Content-Type'] = self.api_client.select_header_content_type(['application/json'])
        _auth_settings: List[str] = ['BearerAuth']

        return self.api_client.param_serialize(
            method='POST', resource_path='/api/custom_oauth_profiles',
            path_params=_path_params, query_params=_query_params,
            header_params=_header_params, body=_body_params,
            post_params=_form_params, files=_files,
            auth_settings=_auth_settings, collection_formats=_collection_formats,
            _host=_host, _request_auth=_request_auth,
        )

    @validate_call
    async def update_custom_oauth_profile(
        self,
        id: Annotated[StrictInt, Field(description="Profile ID")],
        name: Annotated[StrictStr, Field(description="Profile name")],
        provider: Annotated[StrictStr, Field(description="App provider name")],
        client_id: Annotated[StrictStr, Field(description="OAuth client ID")],
        client_secret: Annotated[StrictStr, Field(description="OAuth client secret")],
        token: Annotated[Optional[StrictStr], Field(description="Token (Slack only)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CustomOAuthProfile:
        """Update a custom OAuth profile"""

        _param = self._update_serialize(
            id=id, name=name, provider=provider, client_id=client_id,
            client_secret=client_secret, token=token,
            _request_auth=_request_auth, _content_type=_content_type,
            _headers=_headers, _host_index=_host_index,
        )
        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CustomOAuthProfile", '401': "Error", '404': "Error",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data, response_types_map=_response_types_map,
        ).data

    def _update_serialize(self, id, name, provider, client_id, client_secret, token,
                          _request_auth, _content_type, _headers, _host_index) -> RequestSerialized:
        _host = None
        _collection_formats: Dict[str, str] = {}
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}

        if id is not None:
            _path_params['id'] = id

        body: Dict[str, Any] = {
            "name": name,
            "provider": provider,
            "data": {"client_id": client_id, "client_secret": client_secret},
        }
        if token is not None:
            body["data"]["token"] = token
        _body_params = body

        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])
        _header_params['Content-Type'] = self.api_client.select_header_content_type(['application/json'])
        _auth_settings: List[str] = ['BearerAuth']

        return self.api_client.param_serialize(
            method='PUT', resource_path='/api/custom_oauth_profiles/{id}',
            path_params=_path_params, query_params=_query_params,
            header_params=_header_params, body=_body_params,
            post_params=_form_params, files=_files,
            auth_settings=_auth_settings, collection_formats=_collection_formats,
            _host=_host, _request_auth=_request_auth,
        )

    @validate_call
    async def delete_custom_oauth_profile(
        self,
        id: Annotated[StrictInt, Field(description="Profile ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Dict[str, Any]:
        """Delete a custom OAuth profile"""

        _param = self._get_serialize(
            id=id, _request_auth=_request_auth, _content_type=_content_type,
            _headers=_headers, _host_index=_host_index,
        )
        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object", '401': "Error", '404': "Error",
        }
        response_data = await self.api_client.call_api(
            *self.api_client.param_serialize(
                method='DELETE', resource_path='/api/custom_oauth_profiles/{id}',
                path_params={'id': id}, query_params=[], header_params=_headers or {},
                body=None, post_params=[], files={},
                auth_settings=['BearerAuth'], collection_formats={},
                _host=None, _request_auth=_request_auth,
            ),
            _request_timeout=_request_timeout,
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data, response_types_map=_response_types_map,
        ).data
